name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test XYZ
          conclusion: ${{ job.status }}
          output: |
            {"summary":${{ steps.test.outputs.summary }}}
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
